[package]
name = "rustypi"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "1.0.0"
rp235x-hal = { version = "0.2.0", features = ["rt", "critical-section-impl"] }
embedded-hal = "1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1