[package]
name = "rustypico"
version = "0.1.0"
edition = "2021"
authors = ["Luis <your-email@example.com>"]
description = "A Rust embedded project for Raspberry Pi Pico 2 (RP2350)"
license = "MIT OR Apache-2.0"
categories = ["embedded", "hardware-support", "no-std"]
keywords = ["embedded", "rp2350", "pico2", "raspberry-pi"]

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.7"
embedded-hal = "1.0.0"
defmt = "0.3"
defmt-rtt = "0.4.0"
panic-halt = "0.2.0"
rp235x-hal = { version = "0.3.0", features = ["binary-info", "critical-section-impl", "rt", "defmt"] }

[profile.dev]
debug = 2
lto = false
opt-level = "s"

[profile.release]
debug = 2
lto = true
opt-level = "z"

[[bin]]
name = "rustypico"
test = false
bench = false