# Cargo Configuration for RP2350 (Pico 2)

[build]
# Set the default target to match the Cortex-M33 in the RP2350
target = "thumbv8m.main-none-eabihf"

# This is the hard-float ABI for Arm mode.
# The FPU is enabled by default, and float function arguments use FPU registers.
[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    # Required for defmt RTT symbol table so probe-rs can decode logs
    "-C", "link-arg=-Tdefmt.x",
    "-C", "target-cpu=cortex-m33",
]

# Use probe-rs for loading and debugging with Pico probe
# Load an ELF, skipping unchanged flash sectors, verify it, and execute it.
# Note: Newer probe-rs uses --format instead of the old --defmt flag.
runner = "probe-rs run --chip RP2350"

[env]
# Show all logs during development; adjust per-bin if desired
DEFMT_LOG = "debug"